version: '3.8'

services:

  web:
    build: 
        context: .
        dockerfile: Dockerfile 
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
       - ./web/src:/var/www/html/
    
    ports:
      - 8040:80

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql     


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 81:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
      db: