

version: '3'
# networks:
#   connect:
#     driver: bridge
services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'
    # networks:
    #   - connect

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # networks:
    #   - connect
  
  # alertmanager:
  #   image: prom/alertmanager:latest
  #   volumes:
  #     - ./alertmanager.yml:/alertmanager.yml
  #   command:
  #     - '--config.file=/alertmanager.yml'
  #   ports:
  #     - '9093:9093'

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
     - '9093:9093'
    volumes:
      - './alertmanager/:/etc/alertmanager/'
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    # networks:
    #   - connect

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    # networks:
    #   - connect
  

  grafana:
    image: grafana/grafana
    restart: always
    user: "1000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA-USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA-PASSWORD}
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    # networks:
    #   - connect