

global:
  scrape_interval: 5s
  external_labels:
    monitor: 'docker-container-monitor'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']
      
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: docker
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9323']  

  # - job_name: webapp
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['host.docker.internal:3000']
  # - job_name: 'docker'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['127.0.0.1:9323']
  # targets: ['192.168.65.0:9323']  